version: "3.4"
services:
    yacht:
        container_name: yacht
        image: selfhostedpro/yacht:devel
        restart: unless-stopped
        ports:
          - 8000:8000
        volumes:
          - ${CONFIG}/yacht:/config
          - /var/run/docker.sock:/var/run/docker.sock

    vpn:
        container_name: vpn
        image: ghcr.io/bubuntux/nordlynx
        cap_add:
          - NET_ADMIN #required
          - NET_RAW
        restart: unless-stopped
        environment:
          - NET_LOCAL=${NETWORK}
          - PRIVATE_KEY=${PRIVATE_KEY}
          - TZ=${TZ}
        ports:
          - 8080:8080 # Web port 1
          - 9117:9117 # Web port 2
          - 8112:8112 # Deluge web UI and download daemon
          - 9696:9696 # Prowlarr
          - 8989:8989 # Sonarr port
          - 7878:7878 # Radarr port
          - 3579:3579 # Ombi port
        dns:
          - 9.9.9.9 # Use Quad9 DNS to avoid local restriction to access torrent websites in some countries
          - 149.112.112.112

    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest
        restart: unless-stopped
        network_mode: service:vpn # run on the vpn network
        environment:
          - PUID=${PUID} # default user id, defined in .env
          - PGID=${PGID} # default group id, defined in .env
          - TZ=${TZ} # timezone, defined in .env
        volumes:
          - ${ROOT}/deluge:/downloads # downloads folder
          - ${CONFIG}/deluge:/config # config files
          - ${ROOT}/complete/tv:/tv # TV shows folder
          - ${ROOT}/complete/movies:/movies # Movies folder
        # ports:
        #   - 8112:8112

    prowlarr:
        container_name: prowlarr
        image: linuxserver/prowlarr:develop
        restart: unless-stopped
        network_mode: service:vpn # run on the vpn network
        environment:
          - PUID=${PUID} # default user id, defined in .env
          - PGID=${PGID} # default group id, defined in .env
          - UMASK=002
          - TZ=${TZ} # timezone, defined in .env
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONFIG}/prowlarr:/config # config files
          - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
        # ports:
        #   - 9696:9696

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        network_mode: service:vpn # run on the vpn network
        environment:
          - PUID=${PUID} # default user id, defined in .env
          - PGID=${PGID} # default group id, defined in .env
          - TZ=${TZ} # timezone, defined in .env
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONFIG}/sonarr:/config # config files
          - ${ROOT}/complete/tv:/tv # TV shows folder
        # ports:
        #   - 8989:8989

    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        network_mode: service:vpn # run on the vpn network
        environment:
          - PUID=${PUID} # default user id, defined in .env
          - PGID=${PGID} # default group id, defined in .env
          - TZ=${TZ} # timezone, defined in .env
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ${CONFIG}/radarr:/config # config files
          - ${ROOT}/complete/movies:/movies # movies folder
        # ports:
        #   - 7878:7878

    bazarr:
        container_name: bazarr
        image: linuxserver/bazarr
        restart: unless-stopped
        network_mode: service:vpn # run on the vpn network
        environment:
          - PUID=${PUID} # default user id, defined in .env
          - PGID=${PGID} # default group id, defined in .env
          - TZ=${TZ} # timezone, defined in .env
          - UMASK_SET=022 #optional
        volumes:
          - ${CONFIG}/bazarr:/config # config folder
          - ${ROOT}/complete/movies:/movies # movies folder
          - ${ROOT}/complete/tv:/tv # tv shows folder
        # ports:
        #   - 6767:6767

    ombi:
        container_name: ombi
        image: lscr.io/linuxserver/ombi:latest
        restart: unless-stopped
        network_mode: service:vpn # run on the vpn network
        environment:
          - PUID=${PUID} # default user id, defined in .env
          - PGID=${PGID} # default group id, defined in .env
          - TZ=${TZ} # timezone, defined in .env
        # - BASE_URL=/ombi #optional
        volumes:
            - ${CONFIG}/ombi:/config # config folder
        # ports:
        #     - 3579:3579

    plex:
        container_name: plex
        image: plexinc/pms-docker:latest
        restart: unless-stopped
        environment:
          - PUID=${PUID} # default user id, defined in .env
          - PGID=${PGID} # default group id, defined in .env
        restart: unless-stopped
        devices:
          - /dev/dri:/dev/dri
        volumes:
          - ${CONFIG}/plex:/config:rw
          - ${CONFIG}/config/plex/transcode:/transcode # temp transcoded files
          - ${ROOT}/complete/movies:/movies # movies folder
          - ${ROOT}/complete/tv:/tv # tv shows folder
        ports:
          - 32400:32400
          - 8888:8888

volumes:
    yacht: